### ISSUE TITLE
Alphanumeric encoding does not work for '/' character

### ISSUE THREAD

**Issue by mihaigiurgeanu** [kizzx2/haskell-qrcode#4]
If the alphanumeric text contains '/' character, encode fails:

    encode (fromJust $ version 1) L Alphanumeric "/"

retunrs Nothing. All other characters that are valid for Alphanumeric mode work.

**Comment by mihaigiurgeanu** [comment]
The problem is caused by the Hackage version. The git version is fixed, it works well.

**Comment by kizzx2** [comment]
OK, thanks for the detailed report. So I guess I should update your Hackage version.

**Comment by mihaigiurgeanu** [comment]
Yes, a new pacakge version should be uploaded to Hackage with the fix from pull request #3

**Comment by kizzx2** [comment]
Uploaded 0.1.3 on Hackage
